"""Trades route registrations."""

from mccain_capital.handlers import trades as h


def register(app):
    app.add_url_rule("/trades", endpoint="trades_page", view_func=h.trades_page)
    app.add_url_rule(
        "/trades/risk-controls",
        endpoint="trades_risk_controls",
        view_func=h.trades_risk_controls,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/duplicate/<int:trade_id>",
        endpoint="trades_duplicate",
        view_func=h.trades_duplicate,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/delete/<int:trade_id>",
        endpoint="trades_delete",
        view_func=h.trades_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/delete_many",
        endpoint="trades_delete_many",
        view_func=h.trades_delete_many,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/copy_many",
        endpoint="trades_copy_many",
        view_func=h.trades_copy_many,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/edit/<int:trade_id>",
        endpoint="trades_edit",
        view_func=h.trades_edit,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/review/<int:trade_id>",
        endpoint="trades_review",
        view_func=h.trades_review,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/clear", endpoint="trades_clear", view_func=h.trades_clear, methods=["POST"]
    )
    app.add_url_rule(
        "/trades/paste", endpoint="trades_paste", view_func=h.trades_paste, methods=["GET", "POST"]
    )
    app.add_url_rule(
        "/trades/playbook",
        endpoint="trades_playbook",
        view_func=h.trades_playbook,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/new",
        endpoint="trades_new_manual",
        view_func=h.trades_new_manual,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/paste/broker",
        endpoint="trades_paste_broker",
        view_func=h.trades_paste_broker,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/upload/statement",
        endpoint="trades_upload_pdf",
        view_func=h.trades_upload_pdf,
        methods=["GET", "POST"],
    )
    app.add_url_rule(
        "/trades/sync/live",
        endpoint="trades_sync_live",
        view_func=h.trades_sync_live,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/sync/auto/config",
        endpoint="trades_sync_auto_config",
        view_func=h.trades_sync_auto_config,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/sync/auto/run",
        endpoint="trades_sync_auto_run_now",
        view_func=h.trades_sync_auto_run_now,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/sync/job/<job_id>",
        endpoint="trades_sync_job_status",
        view_func=h.trades_sync_job_status,
        methods=["GET"],
    )
    app.add_url_rule(
        "/trades/sync/debug/<path:name>",
        endpoint="trades_sync_debug_file",
        view_func=h.trades_sync_debug_file,
        methods=["GET"],
    )
    app.add_url_rule("/ops/alerts", endpoint="ops_alerts_page", view_func=h.ops_alerts_page)
    app.add_url_rule(
        "/ops/alerts/ack",
        endpoint="ops_alert_ack",
        view_func=h.ops_alert_ack,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/alerts/resolve",
        endpoint="ops_alert_resolve",
        view_func=h.ops_alert_resolve,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/alerts/mute",
        endpoint="ops_alert_mute",
        view_func=h.ops_alert_mute,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/backups/config",
        endpoint="ops_backups_config",
        view_func=h.ops_backups_config,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/backups",
        endpoint="ops_backups_page",
        view_func=h.ops_backups_page,
        methods=["GET"],
    )
    app.add_url_rule(
        "/ops/backups/run",
        endpoint="ops_backups_run_now",
        view_func=h.ops_backups_run_now,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/backups/download/<path:name>",
        endpoint="ops_backups_download",
        view_func=h.ops_backups_download,
        methods=["GET"],
    )
    app.add_url_rule(
        "/ops/backups/restore",
        endpoint="ops_backups_restore",
        view_func=h.ops_backups_restore,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/backups/restore-dry-run",
        endpoint="ops_backups_restore_dry_run",
        view_func=h.ops_backups_restore_dry_run,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/backups/delete",
        endpoint="ops_backups_delete",
        view_func=h.ops_backups_delete,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/jobs/<job_id>",
        endpoint="ops_job_status",
        view_func=h.ops_job_status,
        methods=["GET"],
    )
    app.add_url_rule(
        "/ops/integrity/run",
        endpoint="ops_integrity_run",
        view_func=h.ops_integrity_run,
        methods=["POST"],
    )
    app.add_url_rule(
        "/ops/integrity/job/<job_id>",
        endpoint="ops_integrity_job_status",
        view_func=h.ops_integrity_job_status,
        methods=["GET"],
    )
    app.add_url_rule(
        "/trades/import/rollback",
        endpoint="rollback_import_batch",
        view_func=h.rollback_import_batch,
        methods=["POST"],
    )
    app.add_url_rule(
        "/trades/open-positions",
        endpoint="trades_open_positions",
        view_func=h.trades_open_positions,
    )
    app.add_url_rule(
        "/trades/reviews/rebuild",
        endpoint="trades_rebuild_reviews",
        view_func=h.trades_rebuild_reviews,
        methods=["GET", "POST"],
    )
